name: production
on:
  push:
    branches:
      - dev
jobs:

  deploy:
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
                  cd iwoc2.0
                  git pull
                  pm2 restart dev