name: staging
on:
  push:
    branches:
      - testing
jobs:

  deploy:
    name: Deploy staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
                  cd iwoc2.0
                  git checkout testing
                  git pull
                  npm install
                  pm2 restart dev